###
POST http://localhost:4000/api/create/question
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJIZWN0b3IxMTciLCJlbWFpbCI6ImhlY3RvckBnbWFpbC5jb20iLCJpYXQiOjE2NDg0Mjk4MDh9.91JvzK2w1l4D6ZGe0tZsp5f9k85FaRl32YSch9bV_qw

{
    "question":"How to delete a prop from a object in JS?",
    "description":"I need to delete a propierty from a object in js and clean the object",
    "tags":[1,10]
}


###
PUT http://localhost:4000/api/edit/question/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJIZWN0b3IxMTciLCJlbWFpbCI6ImhlY3RvckBnbWFpbC5jb20iLCJpYXQiOjE2NDg0Mjk4MDh9.91JvzK2w1l4D6ZGe0tZsp5f9k85FaRl32YSch9bV_qw

{
    "question":"How to delete a prop from a object in JavaScript?",
    "description":"I need to delete a propierty from a object in js and clean the object, i need to do it for more than one prop",
    "tags":[1,10]
}